services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:5.5.1
    ports:
      - 2222:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MODE=standalone
    restart: unless-stopped
