services:
  swag:
    image: lscr.io/linuxserver/swag:5.3.1
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - VALIDATION=${VALIDATION}
      - SUBDOMAINS=${SUBDOMAINS}
      - SWAG_AUTORELOAD=true
    volumes:
      - ./swag:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/nginx_status || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped
