watch:
  schedule: "0 */6 * * *"

notif:
  discord:
    webhookURL: WEEBHOOKURLHERE
    mentions:
      - "@here"
    templateBody: |
      Docker tag {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} which you subscribed to through {{ .Entry.Provider }} provider {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }} on {{ .Entry.Image.Domain }} registry (triggered by {{ .Meta.Hostname }} host).

providers:
  docker:
    watchByDefault: true
  dockerfile:
    patterns:
      - "/home/www/proxy/Dockerfile"
