services:

  postgres:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:33.0.0
    environment:
      PUID: ${PUID_NEXTCLOUD}
      PGID: ${PGID_NEXTCLOUD}
      TZ: ${TZ}
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/status.php || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - www_default
      - default

networks:
  www_default:
    external: true
