services:

  postgres:
    image: postgres:18.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:33.0.0
    environment:
      PUID: ${PUID_NEXTCLOUD}
      PGID: ${PGID_NEXTCLOUD}
      TZ: ${TZ}
    volumes:
      - ${NEXTCLOUD_DATA}/config:/config
      - ${NEXTCLOUD_DATA}/data:/data
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - www_default
      - default

networks:
  www_default:
    external: true
