services:
  diun:
    image: crazymax/diun
    command: serve
    volumes:
      - ./diun/data:/data
      - ./diun/config/diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Zurich
    restart: unless-stopped
